name: frog_sqlite
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  drift: ^2.1.0  
  sqlite3: ^2.1.0 
  path: ^1.9.0    

dev_dependencies:
  build_runner: ^2.4.0
  drift_dev: ^2.1.0 
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0

